# crio_insecure_registries:
#   - 10.0.0.2:5000
# crio_registry_auth:
#   - registry: 10.0.0.2:5000
#     username: user
#     password: pass
crio_registries:
  - prefix: docker.io
    insecure: false
    blocked: false
    location: registry-1.docker.io
    unqualified: false
    mirrors:
      - location: 192.168.100.100:5000
        insecure: true
      - location: mirror.gcr.io
        insecure: false