- job_name: qnap-rclone
  relabel_configs:
  - action: hashmod
    modulus: $(SHARDS)
    source_labels:
    - __address__
    target_label: __tmp_hash
  - action: keep
    regex: $(SHARD)
    source_labels:
    - __tmp_hash
  basic_auth:
    username: %(qnap.rclone.user)s
    password: %(qnap.rclone.pass)s
  static_configs:
  - targets: ['192.168.1.10:5572']
- job_name: esphome
  relabel_configs:
  - action: hashmod
    modulus: $(SHARDS)
    source_labels:
    - __address__
    target_label: __tmp_hash
  - action: keep
    regex: $(SHARD)
    source_labels:
    - __tmp_hash
  static_configs:
  - targets: ['192.168.1.193', '192.168.1.242', '192.168.1.243']
- job_name: integrations/haproxy
  static_configs:
  - targets: ['10.43.0.129:9100']
- job_name: rdmstats
  metrics_path: /probe
  params:
    module: ['rdm']
  static_configs:
  - targets: ['http://rdm.rdm.svc.cluster.local:9000/api/get_data?show_dashboard_stats=true']
  relabel_configs:
  - source_labels: [__address__]
    target_label: __param_target
  - source_labels: [__param_target]
    target_label: instance
  - target_label: __address__
    replacement: jsonexporter.rdm.svc.cluster.local:7979


  