all:
  hosts:
    thinkcentre1:
      ansible_host: 192.168.42.200
      ip: 192.168.42.200
      access_ip: 192.168.42.200
    thinkcentre2:
      ansible_host: 192.168.42.201
      ip: 192.168.42.201
      access_ip: 192.168.42.201
    mad-hx90:
      ansible_host: 192.168.42.202
      ip: 192.168.42.202
      access_ip: 192.168.42.202
  children:
    kube_control_plane:
      hosts:
        thinkcentre1:
        thinkcentre2:
    kube_node:
      hosts:
        thinkcentre1:
        thinkcentre2:
        mad-hx90:
    etcd:
      hosts:
        thinkcentre1:
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
